{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/n44/Actions/CloseModalPage_Complete.action",
	"Message": "Deleted Successfully",
	"NumberOfLines": 2,
	"Duration": 2,
	"IsIconHidden": false,
	"Animated": true
}